//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZapSibNeftehim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderComp
    {
        public int ID { get; set; }
        public int orderID { get; set; }
        public string compID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Order Order { get; set; }
    }
}
