//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int IdDeal { get; set; }
        public Nullable<int> IdDemand { get; set; }
        public Nullable<int> IdSupply { get; set; }
    
        public virtual Demand Demand { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
