//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RostelecomMainWIndow
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbRos : DbContext
    {
        public DbRos()
            : base("name=DbRos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllUser> AllUsers { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<EquipmentList> EquipmentLists { get; set; }
        public virtual DbSet<InstalledEquipment> InstalledEquipments { get; set; }
        public virtual DbSet<InstalledService> InstalledServices { get; set; }
        public virtual DbSet<ServicesList> ServicesLists { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
